all:
	echo "clean,make, and build"
build:
	g++ main.cpp array.cpp book.cpp array.h book.h -o library
run:
	./library
debug:
	g++  -g main.cpp array.cpp book.cpp array.h book.h -o library
	gdb ./library
