build:
	g++ main.cpp doublyLinkedList.cpp book.cpp doublyLinkedList.h book.h -o list
run:
	./list
debug:
	g++  -g main.cpp doublyLinkedList.cpp book.cpp doublyLinkedList.h book.h -o library
	gdb ./library
