build:
	g++ main.cpp doublyLinkedList.cpp book.cpp doublyLinkedList.h book.h -o library
run:
	./library
debug:
	g++  -g main.cpp doublyLinkedList.cpp book.cpp doublyLinkedList.h book.h -o library
	gdb ./library
